from __future__ import annotations

from typing import Protocol

from infrastructure.persistence.dto.episode_dto import EpisodeDTO


class EpisodeRepository(Protocol):
    def append_episode(self, episode: EpisodeDTO) -> None: ...
    def settle_episode(self, episode_id: str, pnl: float, t_exit: str) -> None: ...
    def get_open_episodes(self) -> list[EpisodeDTO]: ...
    def get_settled_episodes(self) -> list[EpisodeDTO]: ...
    def replay(self) -> list[EpisodeDTO]: ...
